print ("Biodata Faris Syahluthfi")
print ("=====================================================================")
print ("Assalamu'allaikum")
print ("My name is Faris Syahluthfi")
print ("But you can call me Faris")
print ("My NIM 312010034")
print ("I was born in Jakarta")
print ("And l am 18 years old")
print ("I am very glad if you want to invite my house in Indramayu")
print ("So, don't forget to call me before with the number 085156729622")
print ("Thank you")
print ("Wassalamu'allaikum")
print ("=====================================================================")


